/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 79
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT = 1,
  aux_sym_line_comment_token1 = 2,
  anon_sym_Hypersignal = 3,
  anon_sym_Jamsignal = 4,
  anon_sym_Alongtimeagoina = 5,
  anon_sym_far_COMMAfaraway_DOT_DOT_DOT = 6,
  anon_sym_Maytheforcebewithyou_DOT = 7,
  anon_sym_Cargo = 8,
  anon_sym_UnloadCargo = 9,
  anon_sym_Holotext = 10,
  anon_sym_Credit = 11,
  anon_sym_Signal = 12,
  anon_sym_Iamabigdealintheresistance_DOT = 13,
  anon_sym_Theforceisstrongwiththisone_DOT = 14,
  anon_sym_That_SQUOTEsonehellofapilot_DOT = 15,
  anon_sym_Iamyourfather_DOT = 16,
  anon_sym_Judgemebymysize_COMMAdoyou_QMARK = 17,
  anon_sym_Executeorder = 18,
  anon_sym_Manifest = 19,
  anon_sym_CloseManifest = 20,
  anon_sym_CloseCargo = 21,
  anon_sym_Orderexecuted = 22,
  anon_sym_Starfield = 23,
  sym_identifier = 24,
  anon_sym_DQUOTE = 25,
  anon_sym_DQUOTE2 = 26,
  sym_escape_sequence = 27,
  anon_sym_SQUOTE = 28,
  aux_sym_char_token1 = 29,
  anon_sym_Fromacertainpointofview_DOT = 30,
  anon_sym_That_SQUOTEsimpossible_BANG = 31,
  anon_sym_DASH = 32,
  sym_unsigned_integer = 33,
  sym_string_content = 34,
  sym_source_file = 35,
  sym__definition = 36,
  sym_line_comment = 37,
  sym_extern_function = 38,
  sym_function_definition = 39,
  sym_function_arguments = 40,
  sym_function_argument = 41,
  sym_expression = 42,
  sym_declaration = 43,
  sym_function_call = 44,
  sym_variadic = 45,
  sym_literal = 46,
  sym_string = 47,
  sym_char = 48,
  sym_bool = 49,
  sym_integer = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_function_definition_repeat1 = 52,
  aux_sym_function_arguments_repeat1 = 53,
  aux_sym_function_call_repeat1 = 54,
  aux_sym_string_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = "<(-.-)>",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [anon_sym_Hypersignal] = "Hypersignal",
  [anon_sym_Jamsignal] = "Jamsignal",
  [anon_sym_Alongtimeagoina] = "A long time ago in a",
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = "far, far away...",
  [anon_sym_Maytheforcebewithyou_DOT] = "May the force be with you.",
  [anon_sym_Cargo] = "Cargo",
  [anon_sym_UnloadCargo] = "UnloadCargo",
  [anon_sym_Holotext] = "Holotext",
  [anon_sym_Credit] = "Credit",
  [anon_sym_Signal] = "Signal",
  [anon_sym_Iamabigdealintheresistance_DOT] = "I am a big deal in the resistance.",
  [anon_sym_Theforceisstrongwiththisone_DOT] = "The force is strong with this one.",
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = "That's one hell of a pilot.",
  [anon_sym_Iamyourfather_DOT] = "I am your father.",
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = "Judge me by my size, do you \?",
  [anon_sym_Executeorder] = "Execute order",
  [anon_sym_Manifest] = "Manifest",
  [anon_sym_CloseManifest] = "CloseManifest",
  [anon_sym_CloseCargo] = "CloseCargo",
  [anon_sym_Orderexecuted] = "Order executed",
  [anon_sym_Starfield] = "Starfield",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_char_token1] = "char_token1",
  [anon_sym_Fromacertainpointofview_DOT] = "From a certain point of view.",
  [anon_sym_That_SQUOTEsimpossible_BANG] = "That's impossible!",
  [anon_sym_DASH] = "-",
  [sym_unsigned_integer] = "unsigned_integer",
  [sym_string_content] = "string_content",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_line_comment] = "line_comment",
  [sym_extern_function] = "extern_function",
  [sym_function_definition] = "function_definition",
  [sym_function_arguments] = "function_arguments",
  [sym_function_argument] = "function_argument",
  [sym_expression] = "expression",
  [sym_declaration] = "declaration",
  [sym_function_call] = "function_call",
  [sym_variadic] = "variadic",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [sym_char] = "char",
  [sym_bool] = "bool",
  [sym_integer] = "integer",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_function_arguments_repeat1] = "function_arguments_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [anon_sym_Hypersignal] = anon_sym_Hypersignal,
  [anon_sym_Jamsignal] = anon_sym_Jamsignal,
  [anon_sym_Alongtimeagoina] = anon_sym_Alongtimeagoina,
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = anon_sym_far_COMMAfaraway_DOT_DOT_DOT,
  [anon_sym_Maytheforcebewithyou_DOT] = anon_sym_Maytheforcebewithyou_DOT,
  [anon_sym_Cargo] = anon_sym_Cargo,
  [anon_sym_UnloadCargo] = anon_sym_UnloadCargo,
  [anon_sym_Holotext] = anon_sym_Holotext,
  [anon_sym_Credit] = anon_sym_Credit,
  [anon_sym_Signal] = anon_sym_Signal,
  [anon_sym_Iamabigdealintheresistance_DOT] = anon_sym_Iamabigdealintheresistance_DOT,
  [anon_sym_Theforceisstrongwiththisone_DOT] = anon_sym_Theforceisstrongwiththisone_DOT,
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [anon_sym_Iamyourfather_DOT] = anon_sym_Iamyourfather_DOT,
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = anon_sym_Judgemebymysize_COMMAdoyou_QMARK,
  [anon_sym_Executeorder] = anon_sym_Executeorder,
  [anon_sym_Manifest] = anon_sym_Manifest,
  [anon_sym_CloseManifest] = anon_sym_CloseManifest,
  [anon_sym_CloseCargo] = anon_sym_CloseCargo,
  [anon_sym_Orderexecuted] = anon_sym_Orderexecuted,
  [anon_sym_Starfield] = anon_sym_Starfield,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_char_token1] = aux_sym_char_token1,
  [anon_sym_Fromacertainpointofview_DOT] = anon_sym_Fromacertainpointofview_DOT,
  [anon_sym_That_SQUOTEsimpossible_BANG] = anon_sym_That_SQUOTEsimpossible_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_unsigned_integer] = sym_unsigned_integer,
  [sym_string_content] = sym_string_content,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_line_comment] = sym_line_comment,
  [sym_extern_function] = sym_extern_function,
  [sym_function_definition] = sym_function_definition,
  [sym_function_arguments] = sym_function_arguments,
  [sym_function_argument] = sym_function_argument,
  [sym_expression] = sym_expression,
  [sym_declaration] = sym_declaration,
  [sym_function_call] = sym_function_call,
  [sym_variadic] = sym_variadic,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [sym_bool] = sym_bool,
  [sym_integer] = sym_integer,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_function_arguments_repeat1] = aux_sym_function_arguments_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Hypersignal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Jamsignal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Alongtimeagoina] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Maytheforcebewithyou_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Cargo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UnloadCargo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Holotext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Credit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Iamabigdealintheresistance_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Theforceisstrongwiththisone_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_That_SQUOTEsonehellofapilot_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Iamyourfather_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Executeorder] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Manifest] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CloseManifest] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CloseCargo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Orderexecuted] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Starfield] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Fromacertainpointofview_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_That_SQUOTEsimpossible_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_function_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_variadic] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_id = 2,
  field_name = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_id] = "id",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_count, 1},
  [2] =
    {field_id, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(351);
      ADVANCE_MAP(
        '"', 395,
        '\'', 397,
        '-', 412,
        '0', 413,
        '<', 49,
        'C', 399,
        'E', 409,
        'F', 407,
        'H', 406,
        'J', 400,
        'M', 401,
        'O', 408,
        'S', 404,
        'T', 403,
        'U', 405,
        '\\', 320,
        'f', 402,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(350);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(416);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(398);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(184);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(326);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(69);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(92);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(106);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(102);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(329);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(263);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(221);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(301);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(153);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(336);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(264);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(88);
      END_STATE();
    case 16:
      if (lookahead == ' ') ADVANCE(157);
      END_STATE();
    case 17:
      if (lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(220);
      END_STATE();
    case 19:
      if (lookahead == ' ') ADVANCE(195);
      END_STATE();
    case 20:
      if (lookahead == ' ') ADVANCE(253);
      END_STATE();
    case 21:
      if (lookahead == ' ') ADVANCE(114);
      END_STATE();
    case 22:
      if (lookahead == ' ') ADVANCE(155);
      END_STATE();
    case 23:
      if (lookahead == ' ') ADVANCE(77);
      END_STATE();
    case 24:
      if (lookahead == ' ') ADVANCE(123);
      END_STATE();
    case 25:
      if (lookahead == ' ') ADVANCE(250);
      END_STATE();
    case 26:
      if (lookahead == ' ') ADVANCE(252);
      END_STATE();
    case 27:
      if (lookahead == ' ') ADVANCE(93);
      END_STATE();
    case 28:
      if (lookahead == ' ') ADVANCE(188);
      END_STATE();
    case 29:
      if (lookahead == ' ') ADVANCE(189);
      END_STATE();
    case 30:
      if (lookahead == ' ') ADVANCE(276);
      END_STATE();
    case 31:
      if (lookahead == ' ') ADVANCE(96);
      END_STATE();
    case 32:
      if (lookahead == ' ') ADVANCE(308);
      END_STATE();
    case 33:
      if (lookahead == ' ') ADVANCE(314);
      END_STATE();
    case 34:
      if (lookahead == ' ') ADVANCE(78);
      END_STATE();
    case 35:
      if (lookahead == ' ') ADVANCE(259);
      END_STATE();
    case 36:
      if (lookahead == ' ') ADVANCE(174);
      END_STATE();
    case 37:
      if (lookahead == ' ') ADVANCE(115);
      END_STATE();
    case 38:
      if (lookahead == ' ') ADVANCE(338);
      END_STATE();
    case 39:
      if (lookahead == ' ') ADVANCE(91);
      END_STATE();
    case 40:
      if (lookahead == ' ') ADVANCE(290);
      END_STATE();
    case 41:
      if (lookahead == ' ') ADVANCE(292);
      END_STATE();
    case 42:
      if (lookahead == ' ') ADVANCE(213);
      END_STATE();
    case 43:
      if (lookahead == ' ') ADVANCE(330);
      END_STATE();
    case 44:
      if (lookahead == ' ') ADVANCE(319);
      END_STATE();
    case 45:
      if (lookahead == ' ') ADVANCE(160);
      END_STATE();
    case 46:
      if (lookahead == '!') ADVANCE(411);
      END_STATE();
    case 47:
      if (lookahead == '"') ADVANCE(395);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == 'C') ADVANCE(388);
      if (lookahead == '\\') ADVANCE(320);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 48:
      if (lookahead == '\'') ADVANCE(289);
      END_STATE();
    case 49:
      if (lookahead == '(') ADVANCE(53);
      END_STATE();
    case 50:
      if (lookahead == ')') ADVANCE(68);
      END_STATE();
    case 51:
      if (lookahead == ',') ADVANCE(21);
      END_STATE();
    case 52:
      if (lookahead == ',') ADVANCE(16);
      END_STATE();
    case 53:
      if (lookahead == '-') ADVANCE(62);
      END_STATE();
    case 54:
      if (lookahead == '-') ADVANCE(50);
      END_STATE();
    case 55:
      if (lookahead == '.') ADVANCE(365);
      END_STATE();
    case 56:
      if (lookahead == '.') ADVANCE(366);
      END_STATE();
    case 57:
      if (lookahead == '.') ADVANCE(374);
      END_STATE();
    case 58:
      if (lookahead == '.') ADVANCE(410);
      END_STATE();
    case 59:
      if (lookahead == '.') ADVANCE(373);
      END_STATE();
    case 60:
      if (lookahead == '.') ADVANCE(375);
      END_STATE();
    case 61:
      if (lookahead == '.') ADVANCE(372);
      END_STATE();
    case 62:
      if (lookahead == '.') ADVANCE(54);
      END_STATE();
    case 63:
      if (lookahead == '.') ADVANCE(55);
      END_STATE();
    case 64:
      if (lookahead == '.') ADVANCE(63);
      END_STATE();
    case 65:
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == 'C') ADVANCE(388);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 66:
      if (lookahead == '<') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 67:
      if (lookahead == '<') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(398);
      END_STATE();
    case 68:
      if (lookahead == '>') ADVANCE(352);
      END_STATE();
    case 69:
      if (lookahead == '?') ADVANCE(376);
      END_STATE();
    case 70:
      if (lookahead == 'C') ADVANCE(97);
      if (lookahead == 'M') ADVANCE(81);
      END_STATE();
    case 71:
      if (lookahead == 'C') ADVANCE(98);
      END_STATE();
    case 72:
      if (lookahead == 'M') ADVANCE(81);
      END_STATE();
    case 73:
      if (lookahead == 'a') ADVANCE(270);
      if (lookahead == 'l') ADVANCE(258);
      if (lookahead == 'r') ADVANCE(125);
      END_STATE();
    case 74:
      if (lookahead == 'a') ADVANCE(216);
      if (lookahead == 'u') ADVANCE(113);
      END_STATE();
    case 75:
      if (lookahead == 'a') ADVANCE(222);
      END_STATE();
    case 76:
      if (lookahead == 'a') ADVANCE(300);
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(328);
      END_STATE();
    case 78:
      if (lookahead == 'a') ADVANCE(364);
      END_STATE();
    case 79:
      if (lookahead == 'a') ADVANCE(266);
      END_STATE();
    case 80:
      if (lookahead == 'a') ADVANCE(203);
      END_STATE();
    case 81:
      if (lookahead == 'a') ADVANCE(236);
      END_STATE();
    case 82:
      if (lookahead == 'a') ADVANCE(334);
      END_STATE();
    case 83:
      if (lookahead == 'a') ADVANCE(271);
      END_STATE();
    case 84:
      if (lookahead == 'a') ADVANCE(204);
      END_STATE();
    case 85:
      if (lookahead == 'a') ADVANCE(109);
      END_STATE();
    case 86:
      if (lookahead == 'a') ADVANCE(205);
      END_STATE();
    case 87:
      if (lookahead == 'a') ADVANCE(185);
      END_STATE();
    case 88:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 89:
      if (lookahead == 'a') ADVANCE(279);
      END_STATE();
    case 90:
      if (lookahead == 'a') ADVANCE(232);
      END_STATE();
    case 91:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 92:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'y') ADVANCE(247);
      END_STATE();
    case 93:
      if (lookahead == 'a') ADVANCE(219);
      END_STATE();
    case 94:
      if (lookahead == 'a') ADVANCE(318);
      END_STATE();
    case 95:
      if (lookahead == 'a') ADVANCE(214);
      END_STATE();
    case 96:
      if (lookahead == 'a') ADVANCE(168);
      END_STATE();
    case 97:
      if (lookahead == 'a') ADVANCE(277);
      END_STATE();
    case 98:
      if (lookahead == 'a') ADVANCE(280);
      END_STATE();
    case 99:
      if (lookahead == 'b') ADVANCE(335);
      END_STATE();
    case 100:
      if (lookahead == 'b') ADVANCE(210);
      END_STATE();
    case 101:
      if (lookahead == 'b') ADVANCE(196);
      END_STATE();
    case 102:
      if (lookahead == 'b') ADVANCE(144);
      END_STATE();
    case 103:
      if (lookahead == 'c') ADVANCE(325);
      END_STATE();
    case 104:
      if (lookahead == 'c') ADVANCE(136);
      END_STATE();
    case 105:
      if (lookahead == 'c') ADVANCE(322);
      END_STATE();
    case 106:
      if (lookahead == 'c') ADVANCE(135);
      END_STATE();
    case 107:
      if (lookahead == 'c') ADVANCE(139);
      END_STATE();
    case 108:
      if (lookahead == 'c') ADVANCE(142);
      END_STATE();
    case 109:
      if (lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 110:
      if (lookahead == 'd') ADVANCE(383);
      END_STATE();
    case 111:
      if (lookahead == 'd') ADVANCE(382);
      END_STATE();
    case 112:
      if (lookahead == 'd') ADVANCE(186);
      END_STATE();
    case 113:
      if (lookahead == 'd') ADVANCE(163);
      END_STATE();
    case 114:
      if (lookahead == 'd') ADVANCE(260);
      END_STATE();
    case 115:
      if (lookahead == 'd') ADVANCE(143);
      END_STATE();
    case 116:
      if (lookahead == 'd') ADVANCE(130);
      END_STATE();
    case 117:
      if (lookahead == 'd') ADVANCE(138);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 119:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 120:
      if (lookahead == 'e') ADVANCE(332);
      END_STATE();
    case 121:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 122:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 123:
      if (lookahead == 'e') ADVANCE(333);
      END_STATE();
    case 124:
      if (lookahead == 'e') ADVANCE(208);
      END_STATE();
    case 125:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 126:
      if (lookahead == 'e') ADVANCE(327);
      END_STATE();
    case 127:
      if (lookahead == 'e') ADVANCE(284);
      END_STATE();
    case 128:
      if (lookahead == 'e') ADVANCE(287);
      END_STATE();
    case 129:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 130:
      if (lookahead == 'e') ADVANCE(272);
      END_STATE();
    case 131:
      if (lookahead == 'e') ADVANCE(209);
      END_STATE();
    case 132:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 133:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 134:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 135:
      if (lookahead == 'e') ADVANCE(273);
      END_STATE();
    case 136:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 137:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 138:
      if (lookahead == 'e') ADVANCE(267);
      END_STATE();
    case 139:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 140:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 141:
      if (lookahead == 'e') ADVANCE(274);
      END_STATE();
    case 142:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 143:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 144:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 145:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 146:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 147:
      if (lookahead == 'e') ADVANCE(291);
      END_STATE();
    case 148:
      if (lookahead == 'e') ADVANCE(294);
      END_STATE();
    case 149:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 150:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 151:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 152:
      if (lookahead == 'f') ADVANCE(190);
      END_STATE();
    case 153:
      if (lookahead == 'f') ADVANCE(251);
      END_STATE();
    case 154:
      if (lookahead == 'f') ADVANCE(128);
      END_STATE();
    case 155:
      if (lookahead == 'f') ADVANCE(94);
      END_STATE();
    case 156:
      if (lookahead == 'f') ADVANCE(3);
      END_STATE();
    case 157:
      if (lookahead == 'f') ADVANCE(89);
      END_STATE();
    case 158:
      if (lookahead == 'f') ADVANCE(147);
      END_STATE();
    case 159:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 160:
      if (lookahead == 'f') ADVANCE(261);
      END_STATE();
    case 161:
      if (lookahead == 'g') ADVANCE(223);
      END_STATE();
    case 162:
      if (lookahead == 'g') ADVANCE(239);
      END_STATE();
    case 163:
      if (lookahead == 'g') ADVANCE(129);
      END_STATE();
    case 164:
      if (lookahead == 'g') ADVANCE(240);
      END_STATE();
    case 165:
      if (lookahead == 'g') ADVANCE(241);
      END_STATE();
    case 166:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 167:
      if (lookahead == 'g') ADVANCE(226);
      END_STATE();
    case 168:
      if (lookahead == 'g') ADVANCE(257);
      END_STATE();
    case 169:
      if (lookahead == 'g') ADVANCE(33);
      END_STATE();
    case 170:
      if (lookahead == 'g') ADVANCE(227);
      END_STATE();
    case 171:
      if (lookahead == 'g') ADVANCE(43);
      END_STATE();
    case 172:
      if (lookahead == 'h') ADVANCE(76);
      END_STATE();
    case 173:
      if (lookahead == 'h') ADVANCE(151);
      END_STATE();
    case 174:
      if (lookahead == 'h') ADVANCE(131);
      END_STATE();
    case 175:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 176:
      if (lookahead == 'h') ADVANCE(32);
      END_STATE();
    case 177:
      if (lookahead == 'h') ADVANCE(141);
      END_STATE();
    case 178:
      if (lookahead == 'h') ADVANCE(145);
      END_STATE();
    case 179:
      if (lookahead == 'h') ADVANCE(198);
      END_STATE();
    case 180:
      if (lookahead == 'i') ADVANCE(161);
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 181:
      if (lookahead == 'i') ADVANCE(154);
      END_STATE();
    case 182:
      if (lookahead == 'i') ADVANCE(339);
      END_STATE();
    case 183:
      if (lookahead == 'i') ADVANCE(100);
      END_STATE();
    case 184:
      if (lookahead == 'i') ADVANCE(215);
      if (lookahead == 'o') ADVANCE(233);
      END_STATE();
    case 185:
      if (lookahead == 'i') ADVANCE(229);
      END_STATE();
    case 186:
      if (lookahead == 'i') ADVANCE(302);
      END_STATE();
    case 187:
      if (lookahead == 'i') ADVANCE(228);
      END_STATE();
    case 188:
      if (lookahead == 'i') ADVANCE(234);
      END_STATE();
    case 189:
      if (lookahead == 'i') ADVANCE(235);
      END_STATE();
    case 190:
      if (lookahead == 'i') ADVANCE(124);
      END_STATE();
    case 191:
      if (lookahead == 'i') ADVANCE(306);
      END_STATE();
    case 192:
      if (lookahead == 'i') ADVANCE(307);
      END_STATE();
    case 193:
      if (lookahead == 'i') ADVANCE(126);
      END_STATE();
    case 194:
      if (lookahead == 'i') ADVANCE(218);
      END_STATE();
    case 195:
      if (lookahead == 'i') ADVANCE(293);
      END_STATE();
    case 196:
      if (lookahead == 'i') ADVANCE(166);
      END_STATE();
    case 197:
      if (lookahead == 'i') ADVANCE(211);
      END_STATE();
    case 198:
      if (lookahead == 'i') ADVANCE(296);
      END_STATE();
    case 199:
      if (lookahead == 'i') ADVANCE(298);
      END_STATE();
    case 200:
      if (lookahead == 'i') ADVANCE(167);
      END_STATE();
    case 201:
      if (lookahead == 'i') ADVANCE(158);
      END_STATE();
    case 202:
      if (lookahead == 'i') ADVANCE(170);
      END_STATE();
    case 203:
      if (lookahead == 'l') ADVANCE(371);
      END_STATE();
    case 204:
      if (lookahead == 'l') ADVANCE(363);
      END_STATE();
    case 205:
      if (lookahead == 'l') ADVANCE(362);
      END_STATE();
    case 206:
      if (lookahead == 'l') ADVANCE(243);
      END_STATE();
    case 207:
      if (lookahead == 'l') ADVANCE(245);
      END_STATE();
    case 208:
      if (lookahead == 'l') ADVANCE(110);
      END_STATE();
    case 209:
      if (lookahead == 'l') ADVANCE(212);
      END_STATE();
    case 210:
      if (lookahead == 'l') ADVANCE(121);
      END_STATE();
    case 211:
      if (lookahead == 'l') ADVANCE(256);
      END_STATE();
    case 212:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 213:
      if (lookahead == 'l') ADVANCE(254);
      END_STATE();
    case 214:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 215:
      if (lookahead == 'm') ADVANCE(265);
      END_STATE();
    case 216:
      if (lookahead == 'm') ADVANCE(285);
      END_STATE();
    case 217:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 218:
      if (lookahead == 'm') ADVANCE(149);
      END_STATE();
    case 219:
      if (lookahead == 'm') ADVANCE(5);
      END_STATE();
    case 220:
      if (lookahead == 'm') ADVANCE(337);
      END_STATE();
    case 221:
      if (lookahead == 'm') ADVANCE(137);
      END_STATE();
    case 222:
      if (lookahead == 'n') ADVANCE(181);
      if (lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 223:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 224:
      if (lookahead == 'n') ADVANCE(171);
      END_STATE();
    case 225:
      if (lookahead == 'n') ADVANCE(169);
      END_STATE();
    case 226:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 227:
      if (lookahead == 'n') ADVANCE(86);
      END_STATE();
    case 228:
      if (lookahead == 'n') ADVANCE(316);
      END_STATE();
    case 229:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 230:
      if (lookahead == 'n') ADVANCE(133);
      END_STATE();
    case 231:
      if (lookahead == 'n') ADVANCE(207);
      END_STATE();
    case 232:
      if (lookahead == 'n') ADVANCE(104);
      END_STATE();
    case 233:
      if (lookahead == 'n') ADVANCE(140);
      END_STATE();
    case 234:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 235:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 236:
      if (lookahead == 'n') ADVANCE(201);
      END_STATE();
    case 237:
      if (lookahead == 'o') ADVANCE(206);
      if (lookahead == 'y') ADVANCE(262);
      END_STATE();
    case 238:
      if (lookahead == 'o') ADVANCE(286);
      END_STATE();
    case 239:
      if (lookahead == 'o') ADVANCE(367);
      END_STATE();
    case 240:
      if (lookahead == 'o') ADVANCE(380);
      END_STATE();
    case 241:
      if (lookahead == 'o') ADVANCE(368);
      END_STATE();
    case 242:
      if (lookahead == 'o') ADVANCE(217);
      END_STATE();
    case 243:
      if (lookahead == 'o') ADVANCE(310);
      END_STATE();
    case 244:
      if (lookahead == 'o') ADVANCE(321);
      END_STATE();
    case 245:
      if (lookahead == 'o') ADVANCE(85);
      END_STATE();
    case 246:
      if (lookahead == 'o') ADVANCE(324);
      END_STATE();
    case 247:
      if (lookahead == 'o') ADVANCE(323);
      END_STATE();
    case 248:
      if (lookahead == 'o') ADVANCE(297);
      END_STATE();
    case 249:
      if (lookahead == 'o') ADVANCE(224);
      END_STATE();
    case 250:
      if (lookahead == 'o') ADVANCE(159);
      END_STATE();
    case 251:
      if (lookahead == 'o') ADVANCE(278);
      END_STATE();
    case 252:
      if (lookahead == 'o') ADVANCE(156);
      END_STATE();
    case 253:
      if (lookahead == 'o') ADVANCE(282);
      END_STATE();
    case 254:
      if (lookahead == 'o') ADVANCE(225);
      END_STATE();
    case 255:
      if (lookahead == 'o') ADVANCE(187);
      END_STATE();
    case 256:
      if (lookahead == 'o') ADVANCE(309);
      END_STATE();
    case 257:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 258:
      if (lookahead == 'o') ADVANCE(295);
      END_STATE();
    case 259:
      if (lookahead == 'o') ADVANCE(230);
      END_STATE();
    case 260:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 261:
      if (lookahead == 'o') ADVANCE(283);
      END_STATE();
    case 262:
      if (lookahead == 'p') ADVANCE(127);
      END_STATE();
    case 263:
      if (lookahead == 'p') ADVANCE(255);
      END_STATE();
    case 264:
      if (lookahead == 'p') ADVANCE(197);
      END_STATE();
    case 265:
      if (lookahead == 'p') ADVANCE(248);
      END_STATE();
    case 266:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 267:
      if (lookahead == 'r') ADVANCE(377);
      END_STATE();
    case 268:
      if (lookahead == 'r') ADVANCE(242);
      END_STATE();
    case 269:
      if (lookahead == 'r') ADVANCE(116);
      END_STATE();
    case 270:
      if (lookahead == 'r') ADVANCE(162);
      END_STATE();
    case 271:
      if (lookahead == 'r') ADVANCE(152);
      END_STATE();
    case 272:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 273:
      if (lookahead == 'r') ADVANCE(312);
      END_STATE();
    case 274:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 275:
      if (lookahead == 'r') ADVANCE(249);
      END_STATE();
    case 276:
      if (lookahead == 'r') ADVANCE(148);
      END_STATE();
    case 277:
      if (lookahead == 'r') ADVANCE(164);
      END_STATE();
    case 278:
      if (lookahead == 'r') ADVANCE(107);
      END_STATE();
    case 279:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 280:
      if (lookahead == 'r') ADVANCE(165);
      END_STATE();
    case 281:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 282:
      if (lookahead == 'r') ADVANCE(117);
      END_STATE();
    case 283:
      if (lookahead == 'r') ADVANCE(108);
      END_STATE();
    case 284:
      if (lookahead == 'r') ADVANCE(299);
      END_STATE();
    case 285:
      if (lookahead == 's') ADVANCE(200);
      END_STATE();
    case 286:
      if (lookahead == 's') ADVANCE(119);
      END_STATE();
    case 287:
      if (lookahead == 's') ADVANCE(304);
      END_STATE();
    case 288:
      if (lookahead == 's') ADVANCE(183);
      END_STATE();
    case 289:
      if (lookahead == 's') ADVANCE(1);
      END_STATE();
    case 290:
      if (lookahead == 's') ADVANCE(182);
      END_STATE();
    case 291:
      if (lookahead == 's') ADVANCE(305);
      END_STATE();
    case 292:
      if (lookahead == 's') ADVANCE(313);
      END_STATE();
    case 293:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 294:
      if (lookahead == 's') ADVANCE(199);
      END_STATE();
    case 295:
      if (lookahead == 's') ADVANCE(122);
      END_STATE();
    case 296:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 297:
      if (lookahead == 's') ADVANCE(288);
      END_STATE();
    case 298:
      if (lookahead == 's') ADVANCE(315);
      END_STATE();
    case 299:
      if (lookahead == 's') ADVANCE(202);
      END_STATE();
    case 300:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 301:
      if (lookahead == 't') ADVANCE(173);
      END_STATE();
    case 302:
      if (lookahead == 't') ADVANCE(370);
      END_STATE();
    case 303:
      if (lookahead == 't') ADVANCE(369);
      END_STATE();
    case 304:
      if (lookahead == 't') ADVANCE(378);
      END_STATE();
    case 305:
      if (lookahead == 't') ADVANCE(379);
      END_STATE();
    case 306:
      if (lookahead == 't') ADVANCE(175);
      END_STATE();
    case 307:
      if (lookahead == 't') ADVANCE(176);
      END_STATE();
    case 308:
      if (lookahead == 't') ADVANCE(179);
      END_STATE();
    case 309:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 310:
      if (lookahead == 't') ADVANCE(120);
      END_STATE();
    case 311:
      if (lookahead == 't') ADVANCE(134);
      END_STATE();
    case 312:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 313:
      if (lookahead == 't') ADVANCE(275);
      END_STATE();
    case 314:
      if (lookahead == 't') ADVANCE(194);
      END_STATE();
    case 315:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 316:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 317:
      if (lookahead == 't') ADVANCE(132);
      END_STATE();
    case 318:
      if (lookahead == 't') ADVANCE(177);
      END_STATE();
    case 319:
      if (lookahead == 't') ADVANCE(178);
      END_STATE();
    case 320:
      if (lookahead == 'u') ADVANCE(340);
      if (lookahead == 'x') ADVANCE(347);
      if (lookahead != 0) ADVANCE(396);
      END_STATE();
    case 321:
      if (lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 322:
      if (lookahead == 'u') ADVANCE(317);
      END_STATE();
    case 323:
      if (lookahead == 'u') ADVANCE(281);
      END_STATE();
    case 324:
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 325:
      if (lookahead == 'u') ADVANCE(311);
      END_STATE();
    case 326:
      if (lookahead == 'v') ADVANCE(193);
      END_STATE();
    case 327:
      if (lookahead == 'w') ADVANCE(58);
      END_STATE();
    case 328:
      if (lookahead == 'w') ADVANCE(82);
      END_STATE();
    case 329:
      if (lookahead == 'w') ADVANCE(191);
      END_STATE();
    case 330:
      if (lookahead == 'w') ADVANCE(192);
      END_STATE();
    case 331:
      if (lookahead == 'x') ADVANCE(118);
      END_STATE();
    case 332:
      if (lookahead == 'x') ADVANCE(303);
      END_STATE();
    case 333:
      if (lookahead == 'x') ADVANCE(150);
      END_STATE();
    case 334:
      if (lookahead == 'y') ADVANCE(64);
      END_STATE();
    case 335:
      if (lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 336:
      if (lookahead == 'y') ADVANCE(244);
      END_STATE();
    case 337:
      if (lookahead == 'y') ADVANCE(40);
      END_STATE();
    case 338:
      if (lookahead == 'y') ADVANCE(246);
      END_STATE();
    case 339:
      if (lookahead == 'z') ADVANCE(146);
      END_STATE();
    case 340:
      if (lookahead == '{') ADVANCE(346);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(344);
      END_STATE();
    case 341:
      if (lookahead == '}') ADVANCE(396);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(341);
      END_STATE();
    case 342:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(414);
      END_STATE();
    case 343:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(415);
      END_STATE();
    case 344:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(347);
      END_STATE();
    case 345:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(396);
      END_STATE();
    case 346:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(341);
      END_STATE();
    case 347:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(345);
      END_STATE();
    case 348:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(417);
      END_STATE();
    case 349:
      if (eof) ADVANCE(351);
      ADVANCE_MAP(
        '"', 394,
        '\'', 397,
        '-', 412,
        '0', 413,
        '<', 49,
        'A', 42,
        'C', 73,
        'E', 331,
        'F', 268,
        'H', 237,
        'I', 27,
        'J', 74,
        'M', 75,
        'O', 269,
        'S', 180,
        'T', 172,
        'U', 231,
        'f', 79,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(349);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(416);
      END_STATE();
    case 350:
      if (eof) ADVANCE(351);
      ADVANCE_MAP(
        '"', 394,
        '\'', 397,
        '-', 412,
        '0', 413,
        '<', 49,
        'C', 399,
        'E', 409,
        'F', 407,
        'H', 406,
        'J', 400,
        'M', 401,
        'O', 408,
        'S', 404,
        'T', 403,
        'U', 405,
        'f', 402,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(350);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(416);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(398);
      END_STATE();
    case 351:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 352:
      ACCEPT_TOKEN(anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT);
      END_STATE();
    case 353:
      ACCEPT_TOKEN(anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 354:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '(') ADVANCE(356);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 355:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == ')') ADVANCE(360);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 356:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '-') ADVANCE(358);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 357:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '-') ADVANCE(355);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 358:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '.') ADVANCE(357);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 359:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '<') ADVANCE(354);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(359);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(361);
      END_STATE();
    case 360:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '>') ADVANCE(353);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 361:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 362:
      ACCEPT_TOKEN(anon_sym_Hypersignal);
      END_STATE();
    case 363:
      ACCEPT_TOKEN(anon_sym_Jamsignal);
      END_STATE();
    case 364:
      ACCEPT_TOKEN(anon_sym_Alongtimeagoina);
      END_STATE();
    case 365:
      ACCEPT_TOKEN(anon_sym_far_COMMAfaraway_DOT_DOT_DOT);
      END_STATE();
    case 366:
      ACCEPT_TOKEN(anon_sym_Maytheforcebewithyou_DOT);
      END_STATE();
    case 367:
      ACCEPT_TOKEN(anon_sym_Cargo);
      END_STATE();
    case 368:
      ACCEPT_TOKEN(anon_sym_UnloadCargo);
      END_STATE();
    case 369:
      ACCEPT_TOKEN(anon_sym_Holotext);
      END_STATE();
    case 370:
      ACCEPT_TOKEN(anon_sym_Credit);
      END_STATE();
    case 371:
      ACCEPT_TOKEN(anon_sym_Signal);
      END_STATE();
    case 372:
      ACCEPT_TOKEN(anon_sym_Iamabigdealintheresistance_DOT);
      END_STATE();
    case 373:
      ACCEPT_TOKEN(anon_sym_Theforceisstrongwiththisone_DOT);
      END_STATE();
    case 374:
      ACCEPT_TOKEN(anon_sym_That_SQUOTEsonehellofapilot_DOT);
      END_STATE();
    case 375:
      ACCEPT_TOKEN(anon_sym_Iamyourfather_DOT);
      END_STATE();
    case 376:
      ACCEPT_TOKEN(anon_sym_Judgemebymysize_COMMAdoyou_QMARK);
      END_STATE();
    case 377:
      ACCEPT_TOKEN(anon_sym_Executeorder);
      END_STATE();
    case 378:
      ACCEPT_TOKEN(anon_sym_Manifest);
      END_STATE();
    case 379:
      ACCEPT_TOKEN(anon_sym_CloseManifest);
      END_STATE();
    case 380:
      ACCEPT_TOKEN(anon_sym_CloseCargo);
      END_STATE();
    case 381:
      ACCEPT_TOKEN(anon_sym_CloseCargo);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 382:
      ACCEPT_TOKEN(anon_sym_Orderexecuted);
      END_STATE();
    case 383:
      ACCEPT_TOKEN(anon_sym_Starfield);
      END_STATE();
    case 384:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'C') ADVANCE(385);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 385:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(391);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 386:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(384);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 387:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(390);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 388:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(389);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 389:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(392);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 390:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(381);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 391:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(387);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 392:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(386);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 393:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(393);
      END_STATE();
    case 394:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 395:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 396:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 397:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 398:
      ACCEPT_TOKEN(aux_sym_char_token1);
      END_STATE();
    case 399:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(270);
      if (lookahead == 'l') ADVANCE(238);
      if (lookahead == 'r') ADVANCE(125);
      END_STATE();
    case 400:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(216);
      if (lookahead == 'u') ADVANCE(113);
      END_STATE();
    case 401:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(222);
      END_STATE();
    case 402:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'a') ADVANCE(266);
      END_STATE();
    case 403:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'h') ADVANCE(76);
      END_STATE();
    case 404:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'i') ADVANCE(161);
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 405:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'n') ADVANCE(207);
      END_STATE();
    case 406:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'o') ADVANCE(206);
      if (lookahead == 'y') ADVANCE(262);
      END_STATE();
    case 407:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'r') ADVANCE(242);
      END_STATE();
    case 408:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'r') ADVANCE(116);
      END_STATE();
    case 409:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (lookahead == 'x') ADVANCE(118);
      END_STATE();
    case 410:
      ACCEPT_TOKEN(anon_sym_Fromacertainpointofview_DOT);
      END_STATE();
    case 411:
      ACCEPT_TOKEN(anon_sym_That_SQUOTEsimpossible_BANG);
      END_STATE();
    case 412:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 413:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (lookahead == 'b') ADVANCE(342);
      if (lookahead == 'o') ADVANCE(343);
      if (lookahead == 'x') ADVANCE(348);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(416);
      END_STATE();
    case 414:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(414);
      END_STATE();
    case 415:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(415);
      END_STATE();
    case 416:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(416);
      END_STATE();
    case 417:
      ACCEPT_TOKEN(sym_unsigned_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(417);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 349},
  [2] = {.lex_state = 349},
  [3] = {.lex_state = 349},
  [4] = {.lex_state = 349},
  [5] = {.lex_state = 349},
  [6] = {.lex_state = 349},
  [7] = {.lex_state = 349},
  [8] = {.lex_state = 349},
  [9] = {.lex_state = 349},
  [10] = {.lex_state = 349},
  [11] = {.lex_state = 349},
  [12] = {.lex_state = 349},
  [13] = {.lex_state = 349},
  [14] = {.lex_state = 349},
  [15] = {.lex_state = 349},
  [16] = {.lex_state = 349},
  [17] = {.lex_state = 349},
  [18] = {.lex_state = 349},
  [19] = {.lex_state = 349},
  [20] = {.lex_state = 349},
  [21] = {.lex_state = 349},
  [22] = {.lex_state = 349},
  [23] = {.lex_state = 349},
  [24] = {.lex_state = 349},
  [25] = {.lex_state = 349},
  [26] = {.lex_state = 349},
  [27] = {.lex_state = 349},
  [28] = {.lex_state = 349},
  [29] = {.lex_state = 349},
  [30] = {.lex_state = 349},
  [31] = {.lex_state = 349},
  [32] = {.lex_state = 349},
  [33] = {.lex_state = 349},
  [34] = {.lex_state = 349},
  [35] = {.lex_state = 47, .external_lex_state = 1},
  [36] = {.lex_state = 349},
  [37] = {.lex_state = 349},
  [38] = {.lex_state = 47, .external_lex_state = 1},
  [39] = {.lex_state = 47, .external_lex_state = 1},
  [40] = {.lex_state = 47},
  [41] = {.lex_state = 349},
  [42] = {.lex_state = 349},
  [43] = {.lex_state = 349},
  [44] = {.lex_state = 349},
  [45] = {.lex_state = 349},
  [46] = {.lex_state = 47, .external_lex_state = 1},
  [47] = {.lex_state = 349},
  [48] = {.lex_state = 47},
  [49] = {.lex_state = 349},
  [50] = {.lex_state = 349},
  [51] = {.lex_state = 349},
  [52] = {.lex_state = 47},
  [53] = {.lex_state = 47},
  [54] = {.lex_state = 47},
  [55] = {.lex_state = 349},
  [56] = {.lex_state = 47},
  [57] = {.lex_state = 349},
  [58] = {.lex_state = 66},
  [59] = {.lex_state = 359},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 349},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 349},
  [65] = {.lex_state = 67},
  [66] = {.lex_state = 349},
  [67] = {.lex_state = 66},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 66},
  [70] = {.lex_state = 349},
  [71] = {.lex_state = 66},
  [72] = {.lex_state = 349},
  [73] = {.lex_state = 349},
  [74] = {.lex_state = 349},
  [75] = {.lex_state = 349},
  [76] = {.lex_state = 349},
  [77] = {.lex_state = 66},
  [78] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = ACTIONS(3),
    [anon_sym_Hypersignal] = ACTIONS(1),
    [anon_sym_Jamsignal] = ACTIONS(1),
    [anon_sym_far_COMMAfaraway_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_Maytheforcebewithyou_DOT] = ACTIONS(1),
    [anon_sym_Cargo] = ACTIONS(1),
    [anon_sym_UnloadCargo] = ACTIONS(1),
    [anon_sym_Holotext] = ACTIONS(1),
    [anon_sym_Credit] = ACTIONS(1),
    [anon_sym_Signal] = ACTIONS(1),
    [anon_sym_Theforceisstrongwiththisone_DOT] = ACTIONS(1),
    [anon_sym_That_SQUOTEsonehellofapilot_DOT] = ACTIONS(1),
    [anon_sym_Judgemebymysize_COMMAdoyou_QMARK] = ACTIONS(1),
    [anon_sym_Executeorder] = ACTIONS(1),
    [anon_sym_Manifest] = ACTIONS(1),
    [anon_sym_CloseManifest] = ACTIONS(1),
    [anon_sym_CloseCargo] = ACTIONS(1),
    [anon_sym_Orderexecuted] = ACTIONS(1),
    [anon_sym_Starfield] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_char_token1] = ACTIONS(1),
    [anon_sym_Fromacertainpointofview_DOT] = ACTIONS(1),
    [anon_sym_That_SQUOTEsimpossible_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_unsigned_integer] = ACTIONS(1),
    [sym_string_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym__definition] = STATE(50),
    [sym_line_comment] = STATE(1),
    [sym_extern_function] = STATE(55),
    [sym_function_definition] = STATE(55),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT] = ACTIONS(3),
    [anon_sym_Hypersignal] = ACTIONS(7),
    [anon_sym_Alongtimeagoina] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(11), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    ACTIONS(13), 1,
      anon_sym_Cargo,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(19), 1,
      anon_sym_Starfield,
    STATE(2), 1,
      sym_line_comment,
    STATE(3), 1,
      sym_variadic,
    STATE(7), 1,
      sym_function_arguments,
    STATE(8), 1,
      aux_sym_function_definition_repeat1,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [40] = 10,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(13), 1,
      anon_sym_Cargo,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(21), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(3), 1,
      sym_line_comment,
    STATE(9), 1,
      aux_sym_function_definition_repeat1,
    STATE(10), 1,
      sym_function_arguments,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [74] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(31), 1,
      sym_unsigned_integer,
    STATE(4), 1,
      sym_line_comment,
    STATE(24), 1,
      sym_literal,
    ACTIONS(27), 2,
      anon_sym_Fromacertainpointofview_DOT,
      anon_sym_That_SQUOTEsimpossible_BANG,
    STATE(25), 4,
      sym_string,
      sym_char,
      sym_bool,
      sym_integer,
  [106] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(38), 1,
      anon_sym_Executeorder,
    STATE(20), 1,
      sym_expression,
    ACTIONS(33), 2,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_CloseManifest,
    STATE(5), 2,
      sym_line_comment,
      aux_sym_function_definition_repeat1,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(35), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [133] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(41), 1,
      anon_sym_CloseManifest,
    STATE(5), 1,
      aux_sym_function_definition_repeat1,
    STATE(6), 1,
      sym_line_comment,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [161] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(21), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(7), 1,
      sym_line_comment,
    STATE(9), 1,
      aux_sym_function_definition_repeat1,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [189] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(21), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(5), 1,
      aux_sym_function_definition_repeat1,
    STATE(8), 1,
      sym_line_comment,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [217] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(43), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(5), 1,
      aux_sym_function_definition_repeat1,
    STATE(9), 1,
      sym_line_comment,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [245] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(43), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(10), 1,
      sym_line_comment,
    STATE(12), 1,
      aux_sym_function_definition_repeat1,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [273] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(45), 1,
      anon_sym_CloseManifest,
    STATE(6), 1,
      aux_sym_function_definition_repeat1,
    STATE(11), 1,
      sym_line_comment,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [301] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(17), 1,
      anon_sym_Executeorder,
    ACTIONS(47), 1,
      anon_sym_Maytheforcebewithyou_DOT,
    STATE(5), 1,
      aux_sym_function_definition_repeat1,
    STATE(12), 1,
      sym_line_comment,
    STATE(20), 1,
      sym_expression,
    STATE(23), 2,
      sym_declaration,
      sym_function_call,
    ACTIONS(15), 3,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
  [329] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(7), 1,
      anon_sym_Hypersignal,
    ACTIONS(9), 1,
      anon_sym_Alongtimeagoina,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_line_comment,
    STATE(14), 1,
      aux_sym_source_file_repeat1,
    STATE(50), 1,
      sym__definition,
    STATE(55), 2,
      sym_extern_function,
      sym_function_definition,
  [355] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_Hypersignal,
    ACTIONS(56), 1,
      anon_sym_Alongtimeagoina,
    STATE(50), 1,
      sym__definition,
    STATE(14), 2,
      sym_line_comment,
      aux_sym_source_file_repeat1,
    STATE(55), 2,
      sym_extern_function,
      sym_function_definition,
  [379] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(15), 1,
      sym_line_comment,
    ACTIONS(59), 7,
      anon_sym_Jamsignal,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Cargo,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [395] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(16), 1,
      sym_line_comment,
    ACTIONS(61), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [410] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(63), 1,
      anon_sym_UnloadCargo,
    STATE(17), 1,
      sym_line_comment,
    STATE(19), 1,
      aux_sym_function_arguments_repeat1,
    STATE(37), 1,
      sym_function_argument,
    ACTIONS(65), 3,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [431] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(67), 1,
      anon_sym_UnloadCargo,
    STATE(37), 1,
      sym_function_argument,
    STATE(18), 2,
      sym_line_comment,
      aux_sym_function_arguments_repeat1,
    ACTIONS(69), 3,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [450] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(72), 1,
      anon_sym_UnloadCargo,
    STATE(18), 1,
      aux_sym_function_arguments_repeat1,
    STATE(19), 1,
      sym_line_comment,
    STATE(37), 1,
      sym_function_argument,
    ACTIONS(65), 3,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [471] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(20), 1,
      sym_line_comment,
    ACTIONS(74), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [486] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(21), 1,
      sym_line_comment,
    ACTIONS(76), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [501] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(22), 1,
      sym_line_comment,
    ACTIONS(78), 6,
      anon_sym_Jamsignal,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [516] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(23), 1,
      sym_line_comment,
    ACTIONS(80), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [531] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(82), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [546] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(25), 1,
      sym_line_comment,
    ACTIONS(84), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [561] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(26), 1,
      sym_line_comment,
    ACTIONS(86), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [576] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(27), 1,
      sym_line_comment,
    ACTIONS(88), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [591] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(90), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [606] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(29), 1,
      sym_line_comment,
    ACTIONS(92), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [621] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(30), 1,
      sym_line_comment,
    ACTIONS(94), 6,
      anon_sym_Jamsignal,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
  [636] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(31), 1,
      sym_line_comment,
    ACTIONS(96), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [651] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(32), 1,
      sym_line_comment,
    ACTIONS(98), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [666] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(33), 1,
      sym_line_comment,
    ACTIONS(100), 6,
      anon_sym_Maytheforcebewithyou_DOT,
      anon_sym_Iamabigdealintheresistance_DOT,
      anon_sym_Theforceisstrongwiththisone_DOT,
      anon_sym_That_SQUOTEsonehellofapilot_DOT,
      anon_sym_Executeorder,
      anon_sym_CloseManifest,
  [681] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(13), 1,
      anon_sym_Cargo,
    ACTIONS(19), 1,
      anon_sym_Starfield,
    ACTIONS(102), 1,
      anon_sym_Jamsignal,
    STATE(34), 1,
      sym_line_comment,
    STATE(49), 1,
      sym_variadic,
    STATE(66), 1,
      sym_function_arguments,
  [703] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(104), 1,
      anon_sym_DQUOTE2,
    STATE(35), 1,
      sym_line_comment,
    STATE(39), 1,
      aux_sym_string_repeat1,
    ACTIONS(106), 2,
      sym_string_content,
      sym_escape_sequence,
  [720] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(36), 1,
      sym_line_comment,
    ACTIONS(108), 4,
      anon_sym_UnloadCargo,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [733] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(37), 1,
      sym_line_comment,
    ACTIONS(110), 4,
      anon_sym_UnloadCargo,
      anon_sym_Holotext,
      anon_sym_Credit,
      anon_sym_Signal,
  [746] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(112), 1,
      anon_sym_DQUOTE2,
    ACTIONS(114), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(38), 2,
      sym_line_comment,
      aux_sym_string_repeat1,
  [761] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(117), 1,
      anon_sym_DQUOTE2,
    STATE(38), 1,
      aux_sym_string_repeat1,
    STATE(39), 1,
      sym_line_comment,
    ACTIONS(106), 2,
      sym_string_content,
      sym_escape_sequence,
  [778] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(119), 1,
      anon_sym_CloseCargo,
    ACTIONS(121), 1,
      sym_identifier,
    STATE(40), 1,
      sym_line_comment,
    STATE(53), 1,
      aux_sym_function_call_repeat1,
  [794] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(41), 1,
      sym_line_comment,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [806] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(42), 1,
      sym_line_comment,
    ACTIONS(125), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [818] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(43), 1,
      sym_line_comment,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [830] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(44), 1,
      sym_line_comment,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [842] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(45), 1,
      sym_line_comment,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [854] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(46), 1,
      sym_line_comment,
    ACTIONS(133), 3,
      sym_string_content,
      anon_sym_DQUOTE2,
      sym_escape_sequence,
  [866] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(47), 1,
      sym_line_comment,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [878] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_CloseCargo,
    STATE(40), 1,
      aux_sym_function_call_repeat1,
    STATE(48), 1,
      sym_line_comment,
  [894] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(13), 1,
      anon_sym_Cargo,
    ACTIONS(139), 1,
      anon_sym_Jamsignal,
    STATE(49), 1,
      sym_line_comment,
    STATE(61), 1,
      sym_function_arguments,
  [910] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(50), 1,
      sym_line_comment,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [922] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(51), 1,
      sym_line_comment,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [934] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(119), 1,
      anon_sym_CloseCargo,
    ACTIONS(121), 1,
      sym_identifier,
    STATE(52), 1,
      sym_line_comment,
    STATE(54), 1,
      aux_sym_function_call_repeat1,
  [950] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(145), 1,
      anon_sym_CloseCargo,
    ACTIONS(147), 1,
      sym_identifier,
    STATE(53), 2,
      sym_line_comment,
      aux_sym_function_call_repeat1,
  [964] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_CloseCargo,
    STATE(53), 1,
      aux_sym_function_call_repeat1,
    STATE(54), 1,
      sym_line_comment,
  [980] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(55), 1,
      sym_line_comment,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      anon_sym_Hypersignal,
      anon_sym_Alongtimeagoina,
  [992] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(56), 1,
      sym_line_comment,
    ACTIONS(154), 2,
      anon_sym_CloseCargo,
      sym_identifier,
  [1003] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    STATE(57), 1,
      sym_line_comment,
    ACTIONS(156), 2,
      anon_sym_Iamyourfather_DOT,
      anon_sym_Judgemebymysize_COMMAdoyou_QMARK,
  [1014] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(58), 1,
      sym_line_comment,
  [1024] = 3,
    ACTIONS(160), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(162), 1,
      aux_sym_line_comment_token1,
    STATE(59), 1,
      sym_line_comment,
  [1034] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(164), 1,
      anon_sym_SQUOTE,
    STATE(60), 1,
      sym_line_comment,
  [1044] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(166), 1,
      anon_sym_Jamsignal,
    STATE(61), 1,
      sym_line_comment,
  [1054] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      sym_line_comment,
  [1064] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(170), 1,
      sym_unsigned_integer,
    STATE(63), 1,
      sym_line_comment,
  [1074] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(172), 1,
      anon_sym_UnloadCargo,
    STATE(64), 1,
      sym_line_comment,
  [1084] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(174), 1,
      aux_sym_char_token1,
    STATE(65), 1,
      sym_line_comment,
  [1094] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(139), 1,
      anon_sym_Jamsignal,
    STATE(66), 1,
      sym_line_comment,
  [1104] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(67), 1,
      sym_line_comment,
  [1114] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(178), 1,
      sym_unsigned_integer,
    STATE(68), 1,
      sym_line_comment,
  [1124] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(69), 1,
      sym_line_comment,
  [1134] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(182), 1,
      anon_sym_Orderexecuted,
    STATE(70), 1,
      sym_line_comment,
  [1144] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(184), 1,
      sym_identifier,
    STATE(71), 1,
      sym_line_comment,
  [1154] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(186), 1,
      anon_sym_Orderexecuted,
    STATE(72), 1,
      sym_line_comment,
  [1164] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(188), 1,
      anon_sym_far_COMMAfaraway_DOT_DOT_DOT,
    STATE(73), 1,
      sym_line_comment,
  [1174] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(190), 1,
      anon_sym_UnloadCargo,
    STATE(74), 1,
      sym_line_comment,
  [1184] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(192), 1,
      anon_sym_Manifest,
    STATE(75), 1,
      sym_line_comment,
  [1194] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(194), 1,
      anon_sym_Orderexecuted,
    STATE(76), 1,
      sym_line_comment,
  [1204] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_LPAREN_DASH_DOT_DASH_RPAREN_GT,
    ACTIONS(196), 1,
      sym_identifier,
    STATE(77), 1,
      sym_line_comment,
  [1214] = 1,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 106,
  [SMALL_STATE(6)] = 133,
  [SMALL_STATE(7)] = 161,
  [SMALL_STATE(8)] = 189,
  [SMALL_STATE(9)] = 217,
  [SMALL_STATE(10)] = 245,
  [SMALL_STATE(11)] = 273,
  [SMALL_STATE(12)] = 301,
  [SMALL_STATE(13)] = 329,
  [SMALL_STATE(14)] = 355,
  [SMALL_STATE(15)] = 379,
  [SMALL_STATE(16)] = 395,
  [SMALL_STATE(17)] = 410,
  [SMALL_STATE(18)] = 431,
  [SMALL_STATE(19)] = 450,
  [SMALL_STATE(20)] = 471,
  [SMALL_STATE(21)] = 486,
  [SMALL_STATE(22)] = 501,
  [SMALL_STATE(23)] = 516,
  [SMALL_STATE(24)] = 531,
  [SMALL_STATE(25)] = 546,
  [SMALL_STATE(26)] = 561,
  [SMALL_STATE(27)] = 576,
  [SMALL_STATE(28)] = 591,
  [SMALL_STATE(29)] = 606,
  [SMALL_STATE(30)] = 621,
  [SMALL_STATE(31)] = 636,
  [SMALL_STATE(32)] = 651,
  [SMALL_STATE(33)] = 666,
  [SMALL_STATE(34)] = 681,
  [SMALL_STATE(35)] = 703,
  [SMALL_STATE(36)] = 720,
  [SMALL_STATE(37)] = 733,
  [SMALL_STATE(38)] = 746,
  [SMALL_STATE(39)] = 761,
  [SMALL_STATE(40)] = 778,
  [SMALL_STATE(41)] = 794,
  [SMALL_STATE(42)] = 806,
  [SMALL_STATE(43)] = 818,
  [SMALL_STATE(44)] = 830,
  [SMALL_STATE(45)] = 842,
  [SMALL_STATE(46)] = 854,
  [SMALL_STATE(47)] = 866,
  [SMALL_STATE(48)] = 878,
  [SMALL_STATE(49)] = 894,
  [SMALL_STATE(50)] = 910,
  [SMALL_STATE(51)] = 922,
  [SMALL_STATE(52)] = 934,
  [SMALL_STATE(53)] = 950,
  [SMALL_STATE(54)] = 964,
  [SMALL_STATE(55)] = 980,
  [SMALL_STATE(56)] = 992,
  [SMALL_STATE(57)] = 1003,
  [SMALL_STATE(58)] = 1014,
  [SMALL_STATE(59)] = 1024,
  [SMALL_STATE(60)] = 1034,
  [SMALL_STATE(61)] = 1044,
  [SMALL_STATE(62)] = 1054,
  [SMALL_STATE(63)] = 1064,
  [SMALL_STATE(64)] = 1074,
  [SMALL_STATE(65)] = 1084,
  [SMALL_STATE(66)] = 1094,
  [SMALL_STATE(67)] = 1104,
  [SMALL_STATE(68)] = 1114,
  [SMALL_STATE(69)] = 1124,
  [SMALL_STATE(70)] = 1134,
  [SMALL_STATE(71)] = 1144,
  [SMALL_STATE(72)] = 1154,
  [SMALL_STATE(73)] = 1164,
  [SMALL_STATE(74)] = 1174,
  [SMALL_STATE(75)] = 1184,
  [SMALL_STATE(76)] = 1194,
  [SMALL_STATE(77)] = 1204,
  [SMALL_STATE(78)] = 1214,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variadic, 2, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_arguments_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_arguments, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 8, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_arguments, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 7, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 9, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_argument, 2, 0, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_arguments_repeat1, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_function, 4, 0, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_function, 3, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_function, 5, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [168] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_string_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_string_content] = sym_string_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_string_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_hsl_external_scanner_create(void);
void tree_sitter_hsl_external_scanner_destroy(void *);
bool tree_sitter_hsl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_hsl_external_scanner_serialize(void *, char *);
void tree_sitter_hsl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_hsl_external_scanner_create,
      tree_sitter_hsl_external_scanner_destroy,
      tree_sitter_hsl_external_scanner_scan,
      tree_sitter_hsl_external_scanner_serialize,
      tree_sitter_hsl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "hsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
